const queryKeys = {
  getHotelByID: "getHotelByID",
  getApartmentByID: "getApartmentByID",
  getRoomsByID: "getRoomsByID",
  getRoomsByRoomTypeId: "getRoomsByRoomTypeId",
  getHotelRooms: "getHotelRooms",
  getRoomTypes: "getRoomTypes",
  getRoomType: "getRoomType",
  getHotelUsers: "getHotelUsers",
  getHotelRoles: "getHotelRoles",
  getRoomByID: "getRoomByID",
  getTopHotels: "getTopHotels",
  getTopDestinations: "getTopDestinations",
  getBookingByID: "getBookingByID",
  getReviewByBookingID: "getReviewByBookingID",
  getUserBookings: "getUserBookings",
  getReviewsOnGuest: "getReviewsOnGuest",
  getReviewsOnHost: "getReviewsOnHost",
  getRoomBookings: "getRoomBookings",
  getReviewsStatistics: "getReviewsStatistics",
  searchApartments: "searchApartments",
  getReviews: "getReviews",
  getSeachHotels:"getSeachHotels",
  getServiceFAQs: "getServiceFAQs",
  getLocation: "getLocation",
  getAllFacilities: "getAllFacilities",
  getUserTransactions: "getUserTransactions",
  getUserBalance: "getUserBalance",
  getUserPaymentDetails: "getUserPaymentDetails",
  getBanks: "getBanks",
  verifyPaymentDetails: "verifyPaymentDetails",
  getWishListItems: " getWishListItems"
};

export default queryKeys;
